version: '3'
services:
  nawiri:
    container_name: tunawiri
    image: nawiri/app
    build:
      context: .
      dockerfile: Dockerfile

    stdin_open: true
    tty: true
    ports:
      - "8050:8050"




